version: "3.9"
services:
  # Frontend (Angular) Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Ensure this points to the correct Dockerfile for the frontend
    container_name: frontend
    working_dir: /usr/src/app  # This matches the Dockerfile's WORKDIR
    volumes:
      - ./frontend:/usr/src/app  # Mount the frontend code for live updates
      - /usr/src/app/node_modules  # Mount node_modules separately to avoid conflicts
    ports:
      - "4200:4200"
    command: ["npm", "start"]
    environment:
      - DEBUG=true
    #depends_on:
      #- backend
  #backend:
